//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompSys.TestCase.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestCaseDataEntities : DbContext
    {
        public TestCaseDataEntities()
            : base("name=TestCaseDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_AddOrUpdate> Table_AddOrUpdate { get; set; }
        public virtual DbSet<Table_GetOrAdd> Table_GetOrAdd { get; set; }
        public virtual DbSet<Table_Transfer> Table_Transfer { get; set; }
    }
}
